language: java
install: travis_retry mvn validate clean install --quiet -DskipTests=true -B
script: travis_retry mvn validate clean test --quiet -B
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

